## Get this file from your deployment page at clodu.cbh.kth.se
## Either, paste the entire file or copy the parts you need

## Ensure the username and password are not public, you can use secrets for this or keep the github repo private


name: kthcloud-ci
"on":
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: registry.cloud.cbh.kth.se
        username: robot$deploy-0819b9b6-e000-4a62-87c0-bc0a095a3c28+jonas-test
        password: BKcF5arMfiXg7SFe4JOCKnqG6LOKjtFI
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registry.cloud.cbh.kth.se/deploy-0819b9b6-e000-4a62-87c0-bc0a095a3c28/jonas-test
